### ISSUE TITLE
IHttpContextAccessor Error

### ISSUE THREAD

**Issue by nksraja** [KevinDockx/ImplementingAdvancedRESTfulConcernsAspNetCore3#2]
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Marvin.Cache.Headers.IStoreKeyAccessor Lifetime: Transient ImplementationType: Marvin.Cache.Headers.StoreKeyAccessor': Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Marvin.Cache.Headers.StoreKeyAccessor'.)
Unable to create an object of type 'CourseLibraryContext'.

**Comment by KevinDockx** [comment]
Hello, 

when do you get this error?

**Comment by Avondschool** [comment]
Have it too.
From chapter 7 on. After upgrade Marvin.Chache.Headers from 4.1 to 5.0
When trying to run.
You have to register the default implementation for the IHttpAccessor interface in Configureservices:
services.AddHttpContextAccessor();
