### ISSUE TITLE
Hi Kevin!!Could you please post an example of Cache Expiration and Validation!!

### ISSUE THREAD

**Issue by vidhuamit0606** [KevinDockx/ImplementingAdvancedRESTfulConcernsAspNetCore3#4]
wrt to retail scenario ie. an client app (angular) collecting  product summary from API 
demarcation of data is mostly as is derived from real world retail producr , consider Laptop and its supported Accessories wrt to multiple brands API supports.
ques is how to ensure reliability of data sent in response from API endpoint via a Httpget (api/Laptops/GetProducts?fields=Id)
is maximum mostly considering nature of data , resource representation may be different for each Vendor.

**Comment by KevinDockx** [comment]
Hi,

you can find some examples, including documentation, in the HttpCacheHeaders repo: https://github.com/KevinDockx/HttpCacheHeaders.  Note that the actual caching should be handled by a cache server, it's not the responsibility of the API.  

Hope this helps! :)

**Comment by vidhuamit0606** [comment]
Thanks Kevin
