### ISSUE TITLE
Error on shaping collection resource

### ISSUE THREAD

**Issue by MarkRobles** [KevinDockx/ImplementingAdvancedRESTfulConcernsAspNetCore3#5]
If I shape an author and don´t include the id field, it throw an exception on AuthorsController/GetAuthors on this block because the authorAsDictionary does´t have the id field:

`       var shapedAuthorsWithLinks = shapedAuthors.Select(author =>
            {
                var authorAsDictionary = author as IDictionary<string, object>;
                var authorLinks = CreateLinksForAuthor((Guid)authorAsDictionary["Id"], null);
                authorAsDictionary.Add("links", authorLinks);
                return authorAsDictionary;
            });`

I´m trying to figure out how to fix it.  Some help?

**Comment by KevinDockx** [comment]
Seeing an identifier (be it the full URI or part of the URI - the id - so the full URI can easily be constructed) should always be returned, I'd solve this by automatically including the id even if the user doesn't ask for it.  In the end, server wins :)

**Comment by MarkRobles** [comment]
Sure. Great! Thanks!

I just edited this on the resource parameter class:

`   public string _fields { get; set; } = string.Empty;
        public string Fields
        {
            get => _fields;
            set => _fields = (value != "" && !value.Contains("Id")) ? (value + ",id") : value;
        }`

What do you think? Agree? Bad Practice? Good? Whatever?

**Comment by KevinDockx** [comment]
I'd make it case insensitive, but next to that that should do the trick :)
