### ISSUE TITLE
New property in Author (XML/Input) not Binding

### ISSUE THREAD

**Issue by Khungersumit** [KevinDockx/ImplementingAdvancedRESTfulConcernsAspNetCore3#9]
Hi @KevinDockx 
I added a new property in CreateAuthorRequest named **City** and the same in XML request and this City is not binding when I inspect in Controller. (please check 2 attached screenshots)

It works if we choose media type, : application/json but it doesn't work with XML input

![image](https://user-images.githubusercontent.com/36700687/196723378-c8a6fb14-460d-4645-80fe-a77572bb5e81.png)

![image](https://user-images.githubusercontent.com/36700687/196723599-05ea57ac-206e-4f4e-8ab9-0a0f5d06c501.png)

**Comment by michiproep** [comment]
Hi @Khungersumit ,
I can confirm this. Very strange. I would have to dig in deeper to find out what's going on there...

**Comment by Khungersumit** [comment]
Hi @michiproep 

Thanks please let me know as soon as you get any sln. it is quite frustrating for me to move on from here.

**Comment by KevinDockx** [comment]
Try adding it to the XML in the order you defined it on the class/contract.  Most XML (de)serializers don't allow arbitrary ordering of elements.  Hope this helps :)

**Comment by Khungersumit** [comment]
Hi @KevinDockx 

Nope, I already tried it, but that didn't work.

**Comment by KevinDockx** [comment]
That's odd... that should work.  I just gave it a try on my codebase:

Step 1: add a city property (first one in the class): 
![image](https://user-images.githubusercontent.com/2431035/196883882-a91d8f5b-f6a3-4475-a1f3-5839060053b6.png)

Step 2: adjust the request (keeping in mind the property order): 
![image](https://user-images.githubusercontent.com/2431035/196884038-e4f30014-7287-4321-9935-0034e7d46ad7.png)

Result: 
![image](https://user-images.githubusercontent.com/2431035/196883674-0a28b72f-89a8-432d-babf-144bf2966fe6.png)

**Comment by michiproep** [comment]
Well, this is really odd. When I add it at the beginning, it work. But if I have the property anywhere else in the class it does not.

**Comment by Khungersumit** [comment]
@KevinDockx 
If we compare the same logic of sorting the properties in the request with Dto's order, then how FirstName, LastName, and DateOfBirth are working correctly? 🤔

Our Dto order is: 
FirstName
LastName
DateOfBirth

but in our request order is 
DateOfBirth
FirstName
LastName

and this works 😭

**Comment by Khungersumit** [comment]
> Well, this is really odd. When I add it at the beginning, it work. But if I have the property anywhere else in the class it does not.

@michiproep yes, it is quite odd
https://github.com/KevinDockx/ImplementingAdvancedRESTfulConcernsAspNetCore3/issues/9#issuecomment-1285087375

**Comment by KevinDockx** [comment]
Hmm, that's interesting indeed.  From the looks of it, the default XmlDataContractSerializer does NOT expect properties to be in the order of how they are defined on the class (which is what I would expect), but... in alphabetical order.  Sigh.  That explains why adding the City first works, and adding it at any other place doesn't.  

Anyway, an easy way to solve all of this is by using [DataMember(Order = XXX)] attributes on your properties to define the order in which you want them to be provided in the request.

**Comment by michiproep** [comment]
This sounds like a workaround. Because usually, clients use whatever serialzer on their side.
Every new property would be a breaking change. Also, you cannot relay on the OpenApi descriptors to generate this in the right order.
We need a different XmlSerializer on our side

**Comment by Khungersumit** [comment]
Thanks, @KevinDockx for quickly responding to the queries today, I really appreciate that.

@michiproep I agree with you (_Every new property would be a breaking change_) 

I don't see this a good long-term solution suggested by @KevinDockx in https://github.com/KevinDockx/ImplementingAdvancedRESTfulConcernsAspNetCore3/issues/9#issuecomment-1285103328

**Comment by KevinDockx** [comment]
There's two Xml-related serializers included in .NET.  

XmlSerializer by default serializes in order of how the elements are defined on the class (probably that's why that was on my mind :-)).  As far as deserialization is concerned, the order does not matter.  However, this serializer doesn't support all types that are supported by the XmlDataContractSerializer & doesn't work very well with complex object graphs.

XmlDataContractSerializer by default expects elements to be alphabetically ordered when deserializing.  You can control that behaviour with the DataMember attribute.  This serializer does support more types & complex object graphs, but it does not support arbitrary ordering.  

Expecting the input to be in a certain order and/or setting that order is essentially how WCF, which used that data contract serializer heavily, was able to be relatively fast in (de)serializing complex object graphs, and, probably even more important, was able to support XML schemas and schema validation.  Odd as it may seem at first glance, it serves its purpose and is still pretty common.

**Comment by Khungersumit** [comment]
Okay, thanks for the explanation @KevinDockx 

Setup with _AddXmlDataContractSerializerFormatters()_ sounds weird, could be good as you explained above but the problem I see now is we will have to tell consumers to keep the properties order intact or don't add or remove anything and we will also have to share the entire updated request with the correct properties order to them, also in the future if we want to grow our entities so to accept more inputs we will have to update them first our request ordering new fields.

**Comment by KevinDockx** [comment]
That's indeed all true, but is it so different from other issues that may happen with request with invalid bodies sent by customers?  If the request doesn't go through in this case it's essentially a semantic issue with the request body, not that different from people trying to send over a date in a format you can't parse, or a string when an int is expected, or forgetting a required field, etc.  This time it's, additionally, the order that may be off, but the way to solve that isn't different from how you'd solve the other potential issues I mentioned; it's an error the consumer made, which you can try to avoid by 1) correct documentation upfront & 2) correct detailed feedback in case something goes wrong.  E.g.: ensure the swagger doc is as specific as possible, validate the incoming request (XSD schema validation comes to mind), report invalid input as specific as you can, ... 

I'd simply consider it a system constraint you impose on incoming requests, just as there are so many others.  Just my 2 cents :)

**Comment by michiproep** [comment]
That's all true. But I think, we digged deep enough and -at least to me - it turned out that this issue is not really part of what we're trying to tackle within this repo...

**Comment by KevinDockx** [comment]
Also true  ;-)  I hope you can figure out what the best way forward is, and wish you the best of luck! :)

**Comment by Khungersumit** [comment]
Thanks @KevinDockx 

I agree it is not related to this repos or course issue, but it's good I(we) found and learn new things about the XML serializer behavior using this repo/course which I never encountered before 😊
